# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default='newValueString', max_length=200),
        ),
    ]
