# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 10:31
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default='ckEditorString'),
        ),
    ]
