# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171121_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/$D/'),
        ),
    ]
