# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171121_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimg',
            name='upload_alt',
            field=models.CharField(default='Alt Attribute For Image', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogimg',
            name='upload_image',
            field=models.ImageField(default='blogImg/2017/11/21/david-klaasen-54203.jpg', upload_to='blogImg/%Y/%m/%d/'),
        ),
    ]
