# Generated by Django 2.0 on 2017-12-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sth',
            field=models.CharField(default='ddd', max_length=200),
        ),
    ]
