# Generated by Django 2.0 on 2017-12-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_sth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sth',
        ),
    ]
