# Generated by Django 2.0 on 2017-12-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171228_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_bot_flag',
            field=models.BooleanField(default=False, verbose_name='bottt'),
        ),
    ]
