# Generated by Django 2.0.1 on 2018-01-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180107_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_name',
            new_name='bot_name',
        ),
    ]
